name: pull_tab_menu
description: "PullTabMenu brings elegant context menus to Flutter apps through a discreet, pull-out tab interface. Preserve your interface's clean aesthetic while providing immediate access to actions when users need them. Perfect for creative applications where screen space and functionality must be balanced."
version: 0.2.1
homepage: https://github.com/intuosol/pull_tab_menu
repository: https://github.com/intuosol/pull_tab_menu
topics:
  - ui
  - interactive
  - contextual
  - menu
  - customizable

example:
  path: example

screenshots:
  - description: Basic Example
    path: showcase/basic.gif
  - description: Sketch Pad Example
    path: showcase/sketch_pad.gif
  - description: Customizer
    path: showcase/customizer.gif

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
