name: pull_tab_menu
description: "Elegant context menus for Flutter apps via a discreet pull-out tab. Preserves clean aesthetics while providing quick access to actions."
version: 0.2.2
homepage: https://github.com/intuosol/pull_tab_menu
repository: https://github.com/intuosol/pull_tab_menu
topics:
  - ui
  - interactive
  - contextual
  - menu
  - customizable

example:
  path: example

screenshots:
  - description: Pull Tab Menu Icon
    path: showcase/pull_tab_menu_icon.png

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
